### PR TITLE
chore: add gas snapshot

### PR DESCRIPTION
**Pull request by TomAFrench**
I imagine you're going to get a bunch of gas golfing PRs (I've got one or two) so let's get a baseline.

I've also added a missing SPDX identifier to get rid of one of the warnings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
I can rebase the other branches if this gets merged so that we can compare the gas costs more easily.

**Comment by TomAFrench** [comment]
I noticed that we're inheriting from several of the test contracts so these tests are duplicated in the old snapshot. I've removed them to reduce noise.

**Review by clemlak — APPROVED** [review]

**Comment by clemlak** [comment]
That sounds like a good idea! I'm merging this PR right now, should we rebase all the other branches from this one?

**Comment by TomAFrench** [comment]
Sure thing, looks like there's been other changes which have been merged without updating the snapshot however so it's now stale.

**Pull request merged**
