### PR TITLE
allow usage of poolId = 0 to allow chaining createPool with allocate

### PR DESCRIPTION
**Pull request by ts0yu**
closes https://github.com/primitivefinance/portfolio/issues/299

### CODE REVIEW

**Comment by Alexangelj** [comment]
Ah this is slightly incorrect - it should be checking the `poolId` argument. But thinking about it now... it might be difficult to do this because what if we want to create a pool of the first pair? We can't use the latest pair nonce if there's more than two pairs and we want to use the first one...

Let me think more about this one

**Comment by Alexangelj** [comment]
Btw this is my fault since I didn't describe the problem accurately enough 😅

**Comment by ts0yu** [comment]
oh lmao oops I should have looked closer

**Comment by clemlak** [comment]
Closing this as we have a different fix.

**Pull request closed without merging**
